/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoinsRouteImport } from './routes/coins'
import { Route as CrateKeysRouteImport } from './routes/crate-keys'
import { Route as NewsRouteImport } from './routes/news'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ApiPublicBridgeRouteImport } from './routes/api/public/bridge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsRoute = CoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const CrateKeysRoute = CrateKeysRouteImport.update({
  id: '/crate-keys',
  path: '/crate-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeRoute = ApiPublicBridgeRouteImport.update({
  id: '/api/public/bridge',
  path: '/api/public/bridge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coins': typeof CoinsRoute
  '/crate-keys': typeof CrateKeysRoute
  '/news': typeof NewsRoute
  '/ranks': typeof RanksRoute
  '/staff': typeof StaffRoute
  '/store': typeof StoreRoute
  '/api/public/bridge': typeof ApiPublicBridgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coins': typeof CoinsRoute
  '/crate-keys': typeof CrateKeysRoute
  '/news': typeof NewsRoute
  '/ranks': typeof RanksRoute
  '/staff': typeof StaffRoute
  '/store': typeof StoreRoute
  '/api/public/bridge': typeof ApiPublicBridgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coins': typeof CoinsRoute
  '/crate-keys': typeof CrateKeysRoute
  '/news': typeof NewsRoute
  '/ranks': typeof RanksRoute
  '/staff': typeof StaffRoute
  '/store': typeof StoreRoute
  '/api/public/bridge': typeof ApiPublicBridgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coins'
    | '/crate-keys'
    | '/news'
    | '/ranks'
    | '/staff'
    | '/store'
    | '/api/public/bridge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coins'
    | '/crate-keys'
    | '/news'
    | '/ranks'
    | '/staff'
    | '/store'
    | '/api/public/bridge'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coins'
    | '/crate-keys'
    | '/news'
    | '/ranks'
    | '/staff'
    | '/store'
    | '/api/public/bridge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoinsRoute: typeof CoinsRoute
  CrateKeysRoute: typeof CrateKeysRoute
  NewsRoute: typeof NewsRoute
  RanksRoute: typeof RanksRoute
  StaffRoute: typeof StaffRoute
  StoreRoute: typeof StoreRoute
  ApiPublicBridgeRoute: typeof ApiPublicBridgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins': {
      id: '/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crate-keys': {
      id: '/crate-keys'
      path: '/crate-keys'
      fullPath: '/crate-keys'
      preLoaderRoute: typeof CrateKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge': {
      id: '/api/public/bridge'
      path: '/api/public/bridge'
      fullPath: '/api/public/bridge'
      preLoaderRoute: typeof ApiPublicBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoinsRoute: CoinsRoute,
  CrateKeysRoute: CrateKeysRoute,
  NewsRoute: NewsRoute,
  RanksRoute: RanksRoute,
  StaffRoute: StaffRoute,
  StoreRoute: StoreRoute,
  ApiPublicBridgeRoute: ApiPublicBridgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
